# Generated by Django 4.1.4 on 2023-01-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
